# Generated by Django 4.2.3 on 2023-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
                ('prediction_results', models.JSONField()),
                ('request_start_date', models.DateTimeField(auto_now_add=True)),
                ('request_end_date', models.DateTimeField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
            ],
        ),
    ]
