# Generated by Django 4.2.3 on 2023-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0002_alter_imageprediction_prediction_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprediction',
            name='predicted_label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
